services:
  easydel-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HARDWARE_TYPE: gpu
    image: easydel:gpu-cuda12.8
    container_name: easydel-gpu
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - .:/workspace
      - /dev:/dev
      - /usr/local/cuda:/usr/local/cuda:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.570.133.20:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libcuda.so.570.133.20:/usr/lib/x86_64-linux-gnu/libcuda.so.1:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.570.133.20:/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1:ro
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-modeset
    working_dir: /workspace
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - JAX_PLATFORM_NAME=cuda
    command: bash
